apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = http://localhost:3000

    # [datasource.prometheus]
    # type = Prometheus
    # url = http://prometheus-service:9090
    # isDefault = true

  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:9090
      basicAuth: false
      isDefault: true