apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - replicationcontrollers
  - replicasets
  - deployments
  - statefulsets
  - daemonsets
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch