apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - name: http
    port: {{ .Values.nodeExporter.service.port | int }}
    targetPort: {{ .Values.nodeExporter.service.targetPort | int }}
  type: {{ .Values.nodeExporter.service.type}}