apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: {{ .Values.prometheus.service.port | int }}
    targetPort: {{ .Values.prometheus.service.targetPort | int }}
  type: {{ .Values.prometheus.service.type }}