# Prometheus values
prometheus:
  replicaCount: 1

  image:
    repository: prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090

# Node Exporter values
nodeExporter:
  replicaCount: 1

  image:
    repository: prom/node-exporter
    tag: latest

  service:
    type: ClusterIP
    port: 9100
    targetPort: 9100

# Kube state metrics values
kubeStateMetrics:
  replicaCount: 1

  image:
    repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    tag: v2.3.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
    
# Grafana values
grafana:
  replicaCount: 1

  image:
    repository: grafana/grafana
    tag: latest

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

