apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: {{ .Values.grafana.service.port | int }}
    targetPort: {{ .Values.grafana.service.targetPort | int }}
  type: {{ .Values.grafana.service.type}}