apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: imesh
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
          items:
          - key: grafana.ini
            path: grafana.ini
          - key: datasource.yaml
            path: provisioning/datasources/datasource.yaml